### ISSUE TITLE
Error EPERM when saving file

### ISSUE THREAD

**Issue by SebiSebi** [xylish7/Youtube-Downloader-GUI#2]
It seems that it cannot save the file in a directory that I own. There should be no permission errors. See example below. After listing the error it continues to fetch the data.

[Working](https://pasteboard.co/H7jebrM.png)
[Error](https://pasteboard.co/H7jepXj.png)

**Comment by SebiSebi** [comment]
It does not work even if I open the app as administrator.

**Comment by xylish7** [comment]
Make sure that the app is not blocked by any antivirus software.
